[phases.setup]
commands = [
    "pip install -r requirements.txt"
]

[phases.build]
commands = [
    "python manage.py collectstatic --noinput"
]

[phases.start]
commands = [
    "gunicorn book_management.wsgi --log-file -"
]
